Add missing category sorting for `under18` category
Fixes the following error on `GET /events/{crc2013,ukrc2012}/results`:

    TypeError: Cannot read properties of undefined (reading 'includes')